# Generated by Django 3.2.14 on 2022-07-23 08:55

from django.db import migrations
from django.db.models import F


def set_mobile_number_as_username(apps, schema_editor):
    from django.contrib.auth.models import User
    Profile = apps.get_model("nakhll_market", "Profile")
    # resolve conflicts
    profiles = Profile.objects.raw('''
        select profile.*
        from nakhll_market_profile as profile
        join auth_user as u
            on u.id<>profile."FK_User_id" and
            u.username=profile."MobileNumber"
    ''')
    for profile in profiles:
        user = User.objects.get(username=profile.MobileNumber)
        user.username = user.User_Profile.MobileNumber
        user.save()

    for user in User.objects.all():
        if hasattr(user, 'User_Profile'):
            user.username = user.User_Profile.MobileNumber
            user.save()
        else:
            '''this user has no related profile'''


class Migration(migrations.Migration):

    dependencies = [
        ('nakhll_market', '0154_auto_20220719_1512'),
    ]

    operations = [
        migrations.RunPython(
            set_mobile_number_as_username,
            migrations.RunPython.noop),
    ]
